### ISSUE TITLE
VIPMT source code

### ISSUE THREAD

**Issue by zhouzi180** [nankepan/VIPMT#1]
Thanks for your excellent work, and when will you open VIPMT source code?

**Comment by nankepan** [comment]
Thanks for your interest, the code will be released within a month.

**Comment by zhouzi180** [comment]
你好，
kepan
        
首先，非常感谢你的杰出工作。我深信VIPMT及其代码将成为FSVOS领域的典范，为该领域的研究人员提供宝贵的学习和参考资源。

目前，我也在从事FSVOS领域的相关研究工作。我之前曾与刘老师联系关于代码何时开源的问题，并了解到您正在积极寻找工作，工作十分繁忙。在这种情况下，我有一个紧急的请求，不知道你是否方便将你在YouTube-VIS数据集上训练好的FSISS方法（NTRENet, SSP, VAT, IPMT）的checkpoint提前私发给我呢？
非常感谢你的理解和协助。

祝好，

周子睿南方科技大学
        
            
        
    
         
        
            
                        
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        10/18/2023 22:22
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [nankepan/VIPMT] VIPMT source code (Issue #1)
        
      
    
  

Thanks for your interest, the code will be released within a month.

**Comment by zhouzi180** [comment]
@nankepan 
你好，kepan
        
首先，非常感谢你的杰出工作。我深信VIPMT及其代码将成为FSVOS领域的典范，为该领域的研究人员提供宝贵的学习和参考资源。

目前，我也在从事FSVOS领域的相关研究工作。我之前曾与刘老师联系关于代码何时开源的问题，并了解到您正在积极寻找工作，工作十分繁忙。在这种情况下，我有一个紧急的请求，不知道你是否方便将你在YouTube-VIS数据集上训练好的FSISS方法（NTRENet, SSP, VAT, IPMT）的checkpoint提前私发给我呢？

非常感谢你的理解和协助。

祝好，

Zirui
南方科技大学

**Comment by zhouzi180** [comment]
> Thanks for your interest, the code will be released within a month.

@nankepan Hello, kepan. Sorry to ask again. When will you open VIPMT source code?
